truncate table uifield;
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','login','label','Login','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','login','error','Login cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','password','label','Password','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','password','error','Password cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','firstName','label','First Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','firstName','error','First Name cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','lastName','label','Last Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','lastName','error','Last Name cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','email','label','Email','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','email','error','Wrong email address format','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','locale','label','Locale','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','locale','error','Locale cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','isActive','label','Active','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','title','label','Title','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','title','error','Title cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','title','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','title','control','select:Prof:Prof;Dr:Dr;Mr:Mr;Ms:Ms;Mrs:Mrs;Miss:Miss','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','title','metaposition','1','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','institution','label','Institution','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','institution','error','Institution cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','institution','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','institution','metaposition','10','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','department','label','Department','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','department','metaposition','20','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','building_room','label','Room','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','building_room','metaposition','30','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','address','label','Address','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','address','error','Address cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','address','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','address','metaposition','40','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','city','label','City','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','city','error','City cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','city','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','city','metaposition','50','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','state','label','State','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','state','error','State cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','state','control','select:${states}:code:name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','state','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','state','metaposition','60','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','country','label','Country','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','country','error','Country cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','country','control','select:${countries}:code:name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','country','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','country','metaposition','70','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','zip','label','Zip','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','zip','error','Zip cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','zip','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','zip','metaposition','80','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','phone','label','Phone','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','phone','error','Phone cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','phone','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','phone','metaposition','90','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','fax','label','Fax','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','fax','error','Fax cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','fax','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','fax','metaposition','100','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','password','label','Password','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','password','error','Password cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','password_mismatch','error','The two entries for your password are NOT identical','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','password_invalid','error','Password must be at least 8 characters, containing only letters and numbers, with at least one letter and number','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','password2','label','Re-confirm Password','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','password2','error','Re-confirm password cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','firstName','label','First Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','firstName','error','First Name cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','lastName','label','Last Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','lastName','error','Last Name cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','email','label','Email','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','email','error','Must be correctly formatted','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','email_exists','error','Email already exists in the database','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','locale','label','Locale','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','locale','error','A locale must be selected','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','primaryuserid','label','PI Wasp Username','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','primaryuserid','error','PI Wasp Username cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','primaryuserid_notvalid','error','Not an active registered PI Username','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','primaryuserid','constraint','isValidPiId','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','primaryuserid','metaposition','1','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','title','label','Title','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','title','error','Title cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','title','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','title','control','select:Prof:Prof;Dr:Dr;Mr:Mr;Ms:Ms;Mrs:Mrs;Miss:Miss','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','title','metaposition','5','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','building_room','label','Building / Room','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','building_room','metaposition','30','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','address','label','Street','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','address','metaposition','40','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','phone','label','Phone','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','phone','error','Phone cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','phone','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','phone','metaposition','90','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','fax','label','Fax','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','fax','metaposition','100','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','password','label','Password','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','password','error','Password cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','password_mismatch','error','The two entries for your password are NOT identical','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','password_invalid','error','Password must be at least 8 characters, containing only letters and numbers, with at least one letter and number','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','password2','label','Re-confirm Password','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','password2','error','Re-confirm password cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','firstName','label','First Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','firstName','error','First Name cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','lastName','label','Last Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','lastName','error','Last Name cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','email','label','Email','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','email','error','Wrong email address format','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','locale','label','Locale','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','locale','error','Locale cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','labName','label','Lab Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','labName','error','Lab Name cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','labName','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','labName','metaposition','1','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','title','label','Title','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','title','error','Title cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','title','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','title','control','select:Prof:Prof;Dr:Dr;Mr:Mr;Ms:Ms;Mrs:Mrs;Miss:Miss','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','title','metaposition','5','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','institution','label','Institution','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','institution','error','Institution cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','institution','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','institution','metaposition','10','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','department','error','Department cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','department','label','Department','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','department','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','department','control','select:${department}:departmentId:name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','department','metaposition','20','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','building_room','label','Room','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','building_room','metaposition','30','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','address','label','Address','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','address','error','Address cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','address','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','address','metaposition','40','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','city','label','City','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','city','error','City cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','city','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','city','metaposition','50','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','state','label','State','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','state','control','select:${states}:code:name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','state','metaposition','60','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','country','label','Country','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','country','error','Country cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','country','control','select:${countries}:code:name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','country','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','country','metaposition','70','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','zip','label','Zip','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','zip','error','Zip cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','zip','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','zip','metaposition','80','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','phone','label','Phone','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','phone','error','Phone cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','phone','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','phone','metaposition','90','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','fax','label','Fax','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','fax','metaposition','100','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','name','label','Lab Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','name','error','Lab Name cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','primaryUserId','label','Primary User','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','primaryUserId','error','Please select Primary User','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','departmentId','label','Department','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','departmentId','error','Please select department','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','isActive','label','Active','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','internal_external_lab','label','External/Internal','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','internal_external_lab','error','Please specify lab type (External/Internal)','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','internal_external_lab','control','select:external:External;internal:Internal','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','internal_external_lab','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','internal_external_lab','metaposition','10','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','phone','label','Phone','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','phone','error','Phone cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','phone','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','phone','metaposition','20','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','building_room','label','Room','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','building_room','metaposition','30','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_billing_dept_name','label','Billing Dept. Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_billing_dept_name','metaposition','40','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_contact_name','label','Billing Contact Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_contact_name','metaposition','50','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_institution_name','label','Billing Inst. Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_institution_name','metaposition','60','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_building_room','label','Billing Bld. Room','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_building_room','metaposition','70','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_address','label','Billing Address','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_address','metaposition','80','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_city','label','Billing City','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_city','metaposition','90','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_state','label','Billing State','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_state','control','select:${states}:code:name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_state','metaposition','100','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_country','label','Billing Country','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_country','control','select:${countries}:code:name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_country','metaposition','105','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_zip','label','Billing Zip','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_zip','metaposition','110','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_email','label','Billing Email','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_email','metaposition','120','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_phone','label','Billing Phone','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','billing_phone','metaposition','130','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','research_center_name','label','RS Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','research_center_name','metaposition','140','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','researchcenter_user_list_location','label','RS User URL','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','researchcenter_user_list_location','metaposition','150','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','updated_success','label','Lab was updated','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','created_success','label','Lab was created','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','updated','error','Lab was NOT updated. Please fill in required fields.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','lab','created','error','Lab was NOT created. Please fill in required fields.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','updated_success','label','User was updated','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','created_success','label','User was created','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','updated','error','User was NOT updated. Please fill in required fields.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','created','error','User was NOT created. Please fill in required fields.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labuser','request_title','label','Request Access To Lab','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labuser','request_primaryuser','label','Primary User','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labuser','request_primaryuser','error','Invalid Primary User','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labuser','request_submit','label','Request Access','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labuser','request_success','label','Your request for access has been submitted.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labuser','request_alreadypending','error','Could not request for access to that Lab.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labuser','request_alreadyaccess','error','Could not request for access to that Lab.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','name','label','Lab Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','name','error','Lab Name cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','primaryUserId','label','Primary User','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','primaryUserId','error','Please select Primary User','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','departmentId','label','Department','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','departmentId','error','Please select department','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','internal_external_lab','label','External/Internal','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','internal_external_lab','error','Please specify lab type (External/Internal)','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','internal_external_lab','control','select:external:External;internal:Internal','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','internal_external_lab','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','internal_external_lab','metaposition','10','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','phone','label','Phone','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','phone','error','Phone cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','phone','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','phone','metaposition','20','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','building_room','label','Room','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','building_room','metaposition','30','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_billing_dept_name','label','Billing Dept. Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_billing_dept_name','metaposition','40','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_contact_name','label','Billing Contact Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_contact_name','metaposition','50','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_institution_name','label','Billing Inst. Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_institution_name','metaposition','60','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_building_room','label','Billing Bld. Room','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_building_room','metaposition','70','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_address','label','Billing Address','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_address','metaposition','80','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_city','label','Billing City','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_city','metaposition','90','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_state','label','Billing State','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_state','control','select:${states}:code:name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_state','metaposition','100','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_country','label','Billing Country','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_country','control','select:${countries}:code:name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_country','metaposition','105','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_zip','label','Billing Zip','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_zip','metaposition','110','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_email','label','Billing Email','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_email','metaposition','120','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_phone','label','Billing Phone','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','billing_phone','metaposition','130','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','research_center_name','label','RS Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','research_center_name','metaposition','130','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','researchcenter_user_list_location','label','RS User URL','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labPending','researchcenter_user_list_location','metaposition','140','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','login_title','label','Login Page','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','auth_login_validate','error','Please provide your user login name AND password.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','login_failed','error','Your login attempt was not successful. Try again.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','login_reason','label','Reason','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','login_user','label','User','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','login_password','label','Password','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','login','data','Login','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','login_anchor_forgotpass','label','Forgot Password','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','login_anchor_newuser','label','New User','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','login_anchor_newpi','label','New PI','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','login_anchor_about','label','About','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','forgotpassword_title','label','Reset Password Request','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','forgotpassword_user','label','Username','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','forgotpassword','data','Submit','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','forgotpassword_missingparam','error','Please provide values for all fields','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','forgotpassword_captcha','error','Captcha text incorrect','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','forgotpassword_username','error','A user with the supplied username does not exist','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','forgotpassword_captcha','label','Captcha text','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_title1','label','Reset Password: Step 1','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_title2','label','Reset Password: Step 2','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_user','label','Username','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_authcode','label','Auth Code','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_password1','label','New Password','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_password2','label','Confirm New Password','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_captcha','label','Captcha text','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword','data','Submit','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_noauthcode','error','No authorization code provided','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_missingparam','error','Please provide values for all fields','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_badauthcode','error','Invalid authorization code provided','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_captcha','error','Captcha text incorrect','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_username','error','A user with the supplied username does not exist','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_wronguser','error','Username and authorization code provided do not match','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_new_mismatch','error','The two entries for your NEW password are NOT identical','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_new_invalid','error','New password must be at least 8 characters, containing only letters and numbers, with at least one letter and number','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_instructions','label','New Password Requirements:<br />At least 8 characters in length<br />Only letters & numbers permitted (no spaces, etc)<br />At least one letter and one number<br />','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpasswordemailsent_title','label','Reset Password Request: Email Sent','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpasswordemailsent','data','An email has been sent to your registered email address containing an authorization code. Please click the link within this email or alternatively <a href','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpasswordok_title','label','Reset Password: Complete','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpasswordok','label','Your password has been reset. Click <a href<="" td=""></a>','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','mypassword_title','label','Change Password','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','mypassword_instructions','label','New Password Requirements:<br />At least 8 characters in length<br />Only letters & numbers permitted (no spaces, etc)<br />At least one letter and one number<br />','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','mypassword_oldpassword','label','Old Password','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','mypassword_newpassword1','label','New Password','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','mypassword_newpassword2','label','Confirm New Password','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','mypassword','data','Submit','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','mypassword_missingparam','error','Please provide values for all fields','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','mypassword_cur_mismatch','error','Your old password does NOT match the password in our database','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','mypassword_new_mismatch','error','The two entries for your NEW password are NOT identical','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','mypassword_nodiff','error','Your old and new passwords may NOT be the same','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','mypassword_new_invalid','error','New password must be at least 8 characters, containing only letters and numbers, with at least one letter and number','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','mypassword_ok','label','Password Has Been Changed','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','confirmemail_badauthcode','error','Invalid authorization code provided','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','confirmemail_corruptemail','error','email address in url cannot be decoded','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','confirmemail_bademail','error','email address is incorrect','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','confirmemail_wronguser','error','User email address and authorization code provided do not match','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','confirmemail_captcha','error','Captcha text incorrect','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','confirmemail_title','label','Confirm Email Address','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','confirmemail_email','label','Email Address','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','confirmemail_authcode','label','Auth code','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','confirmemail_captcha','label','Captcha text','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','confirmemail','data','Submit','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','emailconfirmed_title','label','Email Address Confirmed','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','list_title','label','Department List','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','list_create','label','Create Department','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','list_department','label','Department Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','list','data','Submit','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','list_missingparam','error','Please provide a department name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','list_department_exists','error','Department already exists','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','list_ok','label','New department has been created','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','jobDraft','name','label','Job Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','jobDraft','name','error','Job Name Must Not Be Empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','jobDraft','labId','label','Lab','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','jobDraft','labId','error','Lab Must Not Be Empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','jobDraft','workflowId','label','Workflow','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','jobDraft','workflowId','error','Workflow Must Not Be Empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','workflow','label','LABEL:ampliconSeq','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','cgh','workflow','label','LABEL:cgh','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','workflow','label','LABEL:chipSeq','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','controlMicroarray','workflow','label','LABEL:controlMicroarray','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','controlSeq','workflow','label','LABEL:controlSeq','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','deNovoSeq','workflow','label','LABEL:deNovoSeq','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','digitalExpressionProfiling','workflow','label','LABEL:digitalExpressionProfiling','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','directionalRnaSeq','workflow','label','LABEL:directionalRnaSeq','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','geneExpressionSeq','workflow','label','LABEL:geneExpressionSeq','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','helpTag','workflow','label','LABEL:helpTag','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','matePairSeq','workflow','label','LABEL:matePairSeq','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','microarrayChip','workflow','label','LABEL:microarrayChip','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','microarrayGeneExpression','workflow','label','LABEL:microarrayGeneExpression','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','microarrayHelp','workflow','label','LABEL:microarrayHelp','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','mirnaSeq','workflow','label','LABEL:mirnaSeq','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','otherSeqDnaSamples','workflow','label','LABEL:otherSeqDnaSamples','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','otherSeqRnaSamples','workflow','label','LABEL:otherSeqRnaSamples','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','resequencing','workflow','label','LABEL:resequencing','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','rnaSeq','workflow','label','LABEL:rnaSeq','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','seqCap','workflow','label','LABEL:seqCap','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','samples','data','samplefile;chipseqSample','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','platform','label','Platform','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','platform','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','platform','error','Platform cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','platform','control','select:HISeq2000:HISeq2000','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','platform','metaposition','100','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','readlength','label','Read Length','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','readlength','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','readlength','error','readlength cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','readlength','control','select:100:100 bp; 150: 150bp','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','readlength','metaposition','110','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','readtype','label','Read Type','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','readtype','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','readtype','error','readtype cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','readtype','control','select:single:Single-End Read; pair:Pair-End Read','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','readtype','metaposition','120','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','antibody','label','Anti Body','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','antibody','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','antibody','error','antibody cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','antibody','control','select:abc:abc;def:def;ghi:ghi','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','antibody','metaposition','130','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','pcrprimers','label','PCR Primers','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','pcrprimers','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','pcrprimers','error','pcrprimers cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','pcrprimers','control','select:xyz:xyz','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqdna','pcrprimers','metaposition','140','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','samples','data','samplefile;ampliconSample','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','platform','label','Platform','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','platform','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','platform','error','Platform cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','platform','control','select:HISeq2000:HISeq2000','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','platform','metaposition','100','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','readlength','label','Read Length','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','readlength','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','readlength','error','readlength cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','readlength','control','select:100:100 bp; 150: 150bp','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','readlength','metaposition','110','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','readtype','label','Read Type','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','readtype','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','readtype','error','readtype cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','readtype','control','select:single:Single-End Read; pair:Pair-End Read','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','readtype','metaposition','120','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','antibody','label','Anti Body','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','antibody','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','antibody','error','antibody cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','antibody','control','select:abc:abc;def:def;ghi:ghi','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','antibody','metaposition','130','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','pcrprimers','label','PCR Primers','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','pcrprimers','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','pcrprimers','error','pcrprimers cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','pcrprimers','control','select:xyz:xyz','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','ampliconSeq','pcrprimers','metaposition','140','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','name','label','Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','name','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','name','error','Please specify sample name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','typeSampleId','label','Type','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','typeSampleId','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','typeSampleId','error','Please specify type','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','status','label','Status','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','status','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','status','error','Please specify status','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','fileData','label','Sample File','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','fileData','suffix','(10Mb Max)','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','created','data','Sample Created.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','updated','data','Sample Updated.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','removed','data','Sample Removed.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','fileupload_wait','data','File Upload Started. Please Wait ...','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','fileupload_done','data','File Upload Done.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','fileupload_nofile','data','No File Selected.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','material_provided','label','material_provided','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','reference_genome_id','label','reference_genome_id','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','species_id','label','species_id','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','fragment_size','label','fragment_size','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','amount','label','amount','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','concentration','label','concentration','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','260_280','label','260_280','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','260_230','label','260_230','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','volume','label','volume','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','buffer','label','buffer','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','sample_type','label','sample_type','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','antibody_id','label','antibody_id','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','enrich_primer_pair_id','label','enrich_primer_pair_id','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','material_provided','metaposition','10','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','reference_genome_id','metaposition','20','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','species_id','metaposition','30','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','fragment_size','metaposition','40','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','amount','metaposition','50','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','concentration','metaposition','60','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','260_280','metaposition','70','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','260_230','metaposition','80','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','volume','metaposition','90','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','buffer','metaposition','100','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','sample_type','metaposition','110','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','antibody_id','metaposition','120','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','enrich_primer_pair_id','metaposition','130','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','hello','error=Hello World','','','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sample','name','label','Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sample','name','error','Name cannot be null','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','platformunit','barcode','label','Barcode','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','platformunit','barcode','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','platformunit','barcode','error','Barcode cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','platformunit','barcode','metaposition','10','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','platformunit','comment','label','Comment','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','platformunit','comment','error','Comment','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','platformunit','comment','metaposition','20','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','platformunit','version','label','Version','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','platformunit','version','error','VErsioN','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','platformunit','version','metaposition','30','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','platformunit','lanecount','label','Lane Count','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','platformunit','lanecount','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','platformunit','lanecount','error','Lane Count cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','platformunit','lanecount','control','select:1:1;8:8','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','platformunit','lanecount','metaposition','40','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','fmpayment','amount','label','Amount','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','fmpayment','amount','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','fmpayment','amount','metaposition','10','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','fmpayment','amount','error','AmounT cannot be Empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','fmpayment','comment','label','Comment','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','fmpayment','comment','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','fmpayment','comment','metaposition','20','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','fmpayment','comment','error','Comment cannot be Empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','uiField','updated','label','Field Updated','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','uiField','added','label','Field Added','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','uiField','removed','data','Field Deleted','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','uiField','name','label','Field Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','uiField','area','label','Area','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','uiField','locale','label','Locale','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','uiField','attrName','label','Attribute Name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','uiField','attrValue','label','Attribute Value','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','uiField','locale','error','Locale not specified','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','uiField','attrName','suffix','<font color="blue"> see footnote<sup>1</sup> </font>','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','login_submit','label','Login','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','submit','label','Apply for Account','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','select_default','label','-- select --','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','page_title','label','New User','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','confirmemail_submit','label','Submit','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpasswordemailsent','label','An email has been sent to your registered email address containing an authorization code. Please click the link within this email or alternatively <a href="resetpassword.do">click here</a> and enter the authorization code provided. ','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','forgotpassword_submit','label','Submit','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','emailsent','label','Thank you for your account request. You have been sent an email with instructions as to how to confirm your email address. Please click to <a href="wasp/auth/login.do"/>Login</a>','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','auth','resetpassword_submit','label','Submit','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','detail','label','Department','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','detail_missingparam','error','Email is missing','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','detail_administrators','label','Administrators','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','mypassword_submit','label','Submit','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','uiField','not_unique','error','Property already exists','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','antibody','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','antibody','control','select:abc:abc;def:def;ghi:ghi','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','antibody','error','antibody cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','antibody','label','Anti Body','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','antibody','metaposition','130','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','pcrprimers','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','pcrprimers','control','select:xyz:xyz','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','pcrprimers','error','pcrprimers cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','pcrprimers','label','PCR Primers','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','pcrprimers','metaposition','140','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','platform','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','platform','control','select:HISeq2000:HISeq2000','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','platform','error','Platform cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','platform','label','Platform','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','platform','metaposition','100','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','readlength','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','readlength','control','select:100:100 bp; 150: 150bp','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','readlength','error','readlength cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','readlength','label','Read Length','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','readlength','metaposition','110','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','readtype','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','readtype','control','select:single:Single-End Read; pair:Pair-End Read','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','readtype','error','readtype cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','readtype','label','Read Type','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','readtype','metaposition','120','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','chipSeqlibrary','samples','data','samplefile;chipseqSample','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','captcha','error','Captcha text incorrect','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','captcha','label','Captcha text','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','hello','default','error','Hello World','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','action_approve','label','APPROVE','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','action_reject','label','REJECT','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labuser','status_activate','label','Activate','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labuser','status_deactivate','label','Deactivate','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labuser','status_promoteLM','label','PROMOTE to LM','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','labuser','status_demoteLU','label','DEMOTE to LU','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userDetail','page_title','label','User Detail','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userDetail','edit','label','Edit','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userDetail','edit_as_other','label','Edit (as other)','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userDetail','change_password','label','Change Password','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userDetail','cancel','label','Cancel','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userDetail','save','label','Save','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userDetail','lab_users','label','Lab Users','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userDetail','samples','label','Samples','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userDetail','jobs','label','Jobs','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','detail_page_title','label','Department Detail','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','detail_createadmin','label','Create Administrator','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','detail_submit','label','Submit','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','detail_email','label','Administrator''s Email','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','detail_existingadmin','label','Current Administrators','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','detail_labs','label','Labs','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','detail_pendinglabs','label','Pending Labs','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','detail_emailnotfound','error','Email not found','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','detail_ok','label','New Administrator Created','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','department','detail_remove','label','Remove','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','building_room','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','building_room','error','Room cannot be empty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','locale','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','department','control','select:${department}:departmentId:name','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','department','constraint','NotEmpty','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','user','department','error','A department must be selected','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','userPending','emailconfirmed','label','Thank you for confirming your email address. Your principle investigator has been emailed to request confirmation of your eligibility to join their lab and you are advised to contact them to request they do this if your account does not become activated in good time.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','sampleDraft','subtypeSampleId','label','Subtype','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','etx','data','text/x-setext','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','me','data','application/x-troff-me','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','xbm','data','image/x-xbitmap','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','xpm','data','image/x-xbitmap','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','texinfo','data','application/x-texinfo','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','texi','data','application/x-texinfo','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','ief','data','image/ief','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','pbm','data','image/x-portable-bitmap','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','dvi','data','application/x-dvi','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','rgb','data','image/x-rgb','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','src','data','application/x-wais-source','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','wsrc','data','application/x-wais-source','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','man','data','application/x-troff-man','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','pnm','data','image/x-portable-anymap','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','xwd','data','image/x-xwindowdump','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','ras','data','image/x-cmu-rast','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','saveme','data','application/octet-stream','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','dump','data','application/octet-stream','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','hqx','data','application/octet-stream','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','arc','data','application/octet-stream','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','obj','data','application/octet-stream','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','lib','data','application/octet-stream','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','bin','data','application/octet-stream','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','exe','data','application/octet-stream','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','zip','data','application/octet-stream','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','gz','data','application/octet-stream','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','latex','data','application/x-latex','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','pdf','data','application/pdf','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','xml','data','application/xml','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','tex','data','application/x-tex','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','mov','data','video/quicktime','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','qt','data','video/quicktime','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','mime','data','message/rfc822','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','fpx','data','image/vnd.fpx','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','fpix','data','image/vnd.fpx','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','oda','data','application/oda','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','t','data','application/x-troff','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','tr','data','application/x-troff','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','roff','data','application/x-troff','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','pgm','data','image/x-portable-graymap','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','ms','data','application/x-troff-ms','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','movie','data','video/x-sgi-movie','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','mv','data','video/x-sgi-movie','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','tsv','data','text/tab-separated-values','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','contentTypeMap','ppm','data','image/x-portable-pixmap','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','captcha','error','Captcha text incorrect','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','captcha','label','Captcha text','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','submit','label','Apply for Account','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','select_default','label','-- select --','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','page_title','label','New Principle Investigator','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','emailconfirmed','label','Thank you for confirming your email address. Your department administrator has been emailed to request confirmation of your eligibility to register your lab and you are advised to contact them to request they do this if your account does not become activated in good time.','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','emailsent','label','Thank you for your account request. You have been sent an email with instructions as to how to confirm your email address. Please click to <a href="wasp/auth/login.do"/>Login</a>','1');
insert into uifield(locale,area,name,attrName,attrValue,lastupduser) values('en_US','piPending','emailconfirmed_title','label','Email Address Confirmed','1');
