delete from UiField;
update Software s set s.isActive=0;
update ResourceCategory rc set rc.isActive=0;
update SampleTypeCategory stc set stc.isActive=0;
update SampleType st set st.isActive=0;
update FileType ft set ft.isActive=0;
update ResourceType rt set rt.isActive=0;
update SampleSubtype ss set ss.isActive=0;
update Workflow wf set wf.isActive=0;
update Adaptorset a set a.isActive=0;